version: "3.9"
services:
  live_pair_db:
    image: postgres
    restart: always
    container_name: live_pair_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: